### ISSUE TITLE
Autolink - Railroad with Blueprints not working

### ISSUE THREAD

**Issue by RaneEU** [Epp-s-Satisfactory-Mods/AutoLink#2]
Hey,

Just to give you some background:
I’ve been struggling with this game.. I downloaded some blueprints for railroads, and this was my first time using them. I ended up building a very large railway, but then I noticed that many of the railroads weren’t connected. It turns out that some of the blueprints have multiple roads, and this game dosnt link railroads even if it was linked in the SAME blueprint....SOOO DUMB!

After spending 12 hours placing the railroads, it was really frustrating to realize that none of it worked. Now I’ll have to delete everything and manually place the tracks again.

Then I came across your mod, which seems like it could be the solution to my problem, but unfortunately, it’s not working for me. Even with newly placed blueprints, the connections aren’t happening. I’ve posted a video on Discord. Sorry if that bothers you, but gitgub dosnt allow a video if its more than 10mb)

In the first part of the video, I show that newly placed railroads aren’t connecting.
In the second part, I demonstrate how existing railroads, which weren’t connected previously, also aren’t getting connected. It would be amazing if your mod could fix this, even for tracks placed before installing it—but I assume that’s not possible.

do i do something wrong here?

**Comment by Epp-code** [comment]
Rane reached out to me on Discord and my investigation led to discovering some issues with multiple overlapping railroads that I believe I have fixed in v0.4.0, which I've just uploaded.  Thanks Rane!
