### ISSUE TITLE
Floor holes to mahines autolink

### ISSUE THREAD

**Issue by grinkevich** [Epp-s-Satisfactory-Mods/AutoLink#5]
Hello!

I would like to add a new feature request or idea :)
How about... When you put a floor hole right next to the machine to auto-connect with a conveyor lift? I mean, 99% of the time if you placed the hole next to an output... it means you gonna use the conveyor lift to utilise the floor hole, right? The same logic works with floor holes for pipes and the nearest pipe or machine output.

For example.

Put hole:
![image](https://github.com/user-attachments/assets/4a579c94-7e5e-4a74-8561-c9cc91cd1f19)

If it is in the right position, it will perfectly fit to the conveyor lift:
![image](https://github.com/user-attachments/assets/123d44ba-fa9b-41d7-a5e0-9b83bd8b2db6)

Then build the lift:
![image](https://github.com/user-attachments/assets/0cce408d-9385-4d74-9c0d-622415ecff51)

P.S. 
Furthermore, the conveyor lift can be automatically added below the floor (as it is an absolute must anyway), however it is somewhat controversial as sometimes you need to have a long downside lift instead 🤷 

Regards,
Stan

**Comment by grinkevich** [comment]
Actually, it seems like this can be another "Auto-Connect" mod (instead of Auto-Link)... which will build connections between close connections. For example above - machine output and a floor hole. Or machine input and a merger built right next to it. Or for example, a long pipe and you build a pipe junction - it is 100% always you gonna connect this junction to the machine... so on and so on :)
I really miss that mod when I have a row of 30+ machines with a single pipe\conveyor input for that you need to walk through them manually connecting every machine multiple times to very obviously placed pipes\conveyors... 

For example, how cool would it be to connect all machine outputs to the pipe when you place a junction? Right now I am building machine-to-lift connections to handle raw ore input from below the "transport floor", so I am walking now and just placing hundreds of conveyor lifts to already existing holes :)

![image](https://github.com/user-attachments/assets/4e9e8cc9-588d-4a3a-b489-83710884029c)


And there are about ~1000 machines for me to go 😆 

![image](https://github.com/user-attachments/assets/3bb90dfd-79fa-44a3-9171-370927c0bce4)

**Comment by Epp-code** [comment]
I think you're right that would be a different mod.  Automatically creating new entities in the game is actually far, far more complicated than what the mod currently does.  And, as I put in the mod description, I'm trying to leave core gameplay intact.  However, with AutoLink, you should be able to make a tileable blueprint that has the floor holes made and connected and just lay that down repeatedly.  If you're not sure what I mean by that, I put a demonstration video in the mod description that gives one example of what a tileable blueprint can look like.
