### ISSUE TITLE
newly placed hyper tube not working anymore

### ISSUE THREAD

**Issue by e-rwan** [Epp-s-Satisfactory-Mods/AutoLink#6]
hi,
thanks for the mod, apart from this issue its working great for me.
So as the title says newly placed hypertube just won't work work. they won't pull. 
I can see the flowing effect from the entrance and the light is green.
I tried placing an existing blueprint I made for a quick hypercanon, and this one pulls me but instantly push me back.
disassembling and re-assembling won't help(as per the bug you describe in the mod page).
hypertube placed before the mod works as usual.

my mod list is as follow(don't think any of them interfere but just in case):

- infinite zoop,
- infinite nudge,
- production stats,
- flashlight settings,
- no Z fighting,
- all pole with indicator light,
- key bind for blueprint,
- crash site beacons

video exemple: https://drive.google.com/file/d/1wzH3eJerJh7E2VVMOlFvvXpjTd40j2MO/view?usp=sharing

erwan.

**Comment by adrolter** [comment]
I'm having the same problem as of the latest release. I'm also using some other mods in my save, but disabled all of them except AutoLink and the problem remains. Hypertube sections won't snap to entrances on supports, and if I build a segment with two supports and then pop an entrance on one, it won't work. This is the first save where I've really been using hypertubes so I thought I just forgot how they worked and was super perplexed, haha.

Agreed on this being a superb mod, though! Thank you for your work!

**Comment by Epp-code** [comment]
Thanks for the reports!  I must have introduced a regression.  Will look at it now.

**Comment by Epp-code** [comment]
Ok, by fixing the direct linking in 0.4.3, I accidentally enabled hypertubes to link to their supports and now they're basically trying to shoot you into a pole.  I just uploaded a fix in 0.5.0.  I tested manual and blueprint hypertube construction but let me know if anything else comes up.

**Comment by e-rwan** [comment]
express!
yep, working!

**Comment by adrolter** [comment]
LGTM! Thank you!!!
