### ISSUE TITLE
seems to still be an issue with Hypertubes connecting in 0.5.0

### ISSUE THREAD

**Issue by tekman123** [Epp-s-Satisfactory-Mods/AutoLink#7]
i've updated the mod to 0.5.0 and it seems as though the issue might still exist as I still can't connect tubes to pre-existing wall holes with Tubes connecting them.

**Comment by Epp-code** [comment]
Were the wall holes and tubes connected prior to 0.5.0?  Unfortunately, if you built them with 0.4.3, they are gonna be broken and need to be reconstructed.

**Comment by Epp-code** [comment]
I just constructed some wall holes and tubes to be sure and they're working OK for me in 0.5.0.  Try rebuilding them and see what happens - I apologize for the hassle!

**Comment by tekman123** [comment]
It's weird because when I build all new it's fine or if I replace the tube between the holes and even then, it's not all of them so yeah, it's weird lol

**Comment by Epp-code** [comment]
Let me know if you ever reproduce on the newest version.
