### ISSUE TITLE
Short turn railroad dont link

### ISSUE THREAD

**Issue by bfromager** [Epp-s-Satisfactory-Mods/AutoLink#8]
Hi. 
On railroad on 2.5 foundations radius turns links not always works. 
So far it seems ok on 3 foundations radius turns.

**Comment by Epp-code** [comment]
Do you mind posting a screenshot of the radius that doesn’t seem to work? And you say “sometimes” - does that mean it’s inconsistent? That would be very surprising because the code has no randomness - it should either work or not work. So if you can show me a clear case of it not working, I can investigate

**Comment by bfromager** [comment]
Actually i just realized ot not 2.5  but 2 foundations radius turn.
I can provide you blue prints if you want. 

![1](https://github.com/user-attachments/assets/6aa6e61d-a75e-4385-833d-edbe098ffcf5)
![2](https://github.com/user-attachments/assets/cb2f0a41-4cb3-4b3c-892c-aad36e55c876)

On the roundabound i had link issue on B but not on A. But it's not so surprising, Rail in blueprint are bugged as hell, and their behaviors depend on the direction (N-S vs E-W) and the game assume in some case the rail is longer than its display.

**Comment by Epp-code** [comment]
That’s very helpful, thanks. Please do provide the blueprint, too! That will make reproducing much simpler

**Comment by bfromager** [comment]
https://drive.google.com/file/d/1c5YAzuqagUPatUYatwKJ5o42WiNWoAyd/view?usp=sharing
https://drive.google.com/file/d/1e-VRCpOXLhLB9lhtXowkEjdUwGIOAohH/view?usp=sharing

**Comment by Epp-code** [comment]
Thanks for the report!  I was able to reproduce with the tightest possible railroad turns used to make a semi-circle and I just uploaded a fix in 0.5.3.

**Comment by bfromager** [comment]
Excellent! Glad to help, such a must have mod.
